config/routes.rb
Rails.application.routes.draw do
  root 'visitor#main'
  
  get 'register/info1'
  get 'register/info2'
  post 'register/infoget'

  get 'mission/detail/:id', to: 'mission#detail'

  post 'mission/mission_create'                                                           #작성자가 미션 작성하는 페이지
  post 'mission/performed_mission_create'                                                 #수행자가 미션 작성하는 페이지
  post 'mission/performed_mission_create/:id' => 'mission#performed_mission_create'
   
  post 'home/timeline/profile_img_upload/:id' => 'home#profile_img_upload'
   
  post 'home/timeline/:id' => 'home#timeline'                                       
  get 'mission/mission_destroy/:id' => 'mission#mission_destroy'                                  # 작성자가 본인 미션글 삭제
  get 'mission/performed_mission_destroy/:id' => 'mission#performed_mission_destroy'      # 수행자가 본인 수행글 삭제
  
  get 'mission/mission_editview/:id' => 'mission#mission_editview'                            #작성자 본인 글 수정 내용 입력하는 페이지                                                                                
  post 'mission/mission_edit/:id' => 'mission#mission_edit'                                    #입력한 내용이 임시로 날아갔다가 돌아옴

  get 'mission/performed_mission_editview/:id' => 'mission#performed_mission_editview'                            #작성자 본인 글 수정 내용 입력하는 페이지                                                                                
  post 'mission/performed_mission_edit/:id' => 'mission#performed_mission_edit'    
  
  
  post 'mission/missionComment/:id', to: 'mission#missionComment'
  
  
  
  
  
  
  
  get 'visitor/main'

  get 'home/main'
  get 'home/timeline/:id', to: 'home#timeline'
  get 'home/timeline_temp'
  get 'home/missionLike/:id', to: 'home#missionLike'
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks', registrations: "user/registrations", sessions: 'user/sessions' }
  

end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  def main
  end
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/visitor/main.html.erb
  <style type="text/css">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 800px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 1.5em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 2em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 7em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

body > .grid {
  height: 100% !important;
}
.column {
  width: 100% !important;
}
@media(min-width: 600px){
  .duck {
   width: 300px !important; 
  }
}
@media(max-width: 599px){
  .duck {
   width: 200px !important; 
  }
}
</style>

<!--시작 페이지용 navbar-->
<div class="ui container">
  <div class="ui large secondary menu" style="margin-top: 10px">
    <div class="right item">
      <% if user_signed_in? %>
      <%= link_to('로그아웃', destroy_user_session_path, :method => :delete, :class => 'ui black basic button') %>
      <% else %>
      <a class="ui black basic button" href="/users/sign_in">로그인</a>
      <% end %>
    </div>
  </div>
</div>

<!-- Page Contents -->
<div class="ui middle aligned center aligned grid">
  <div class="column">
    <div class="ui text container">
      <h1 class="ui header">
        <div class="ui header">
          <img src="/images/yellow_duck_logo.png" class="image animated infinite jello duck">
        </div>
        <div class="content">
        덕질할땐?
        </div>
      </h1>
      <h2>아임덕</h2>
      <% if user_signed_in? %>
        <%= link_to('메인으로 가기', home_main_path, :class => 'ui yellow button') %>
      <% else %>
        <a class="ui yellow button" href="/users/sign_up">시작하기<i class="right arrow icon"></i></a>
      <% end %>
    </div>
  </div>
</div>
    <img src="/images/perform.png" style="width:100%">
    <img src="/images/perform2.png" style="width:100%">
    <img src="/images/point.png" style="width:100%">
    <a href="https://www.facebook.com/imdukk"><h1>https://www.facebook.com/imdukk</h1></a>
    <h1>페이스북에서 <strong>'아임덕'</strong>을 검색하세요.</h1>
    <br>

<!--<div class="pusher">-->
<!--  <div class="ui vertical masthead center aligned segment">-->

    <!--<div class="ui container">-->
    <!--  <div class="ui large secondary menu">-->
    <!--    <div class="right item">-->
    <!--      <#% if user_signed_in? %>-->
          <%#= link_to('로그아웃', destroy_user_session_path, :method => :delete, :class => 'ui black basic button') %>
    <!--      <#% else %>-->
    <!--      <a class="ui black basic button" href="/users/sign_in">로그인</a>-->
    <!--      <#% end %>-->
    <!--    </div>-->
    <!--  </div>-->
    <!--</div>-->

<!--    <div class="ui text container">-->
<!--      <h1 class="ui header">-->
<!--        <div class="ui header">-->
<!--          <img src="/images/yellow_duck_logo.png" class="image animated infinite jello">-->
<!--        </div>-->
<!--        <div class="content">-->
<!--        덕질할땐?-->
<!--        </div>-->
<!--      </h1>-->
<!--      <h2>아임덕</h2>-->
<!--      <%# if user_signed_in? %>-->
<!--        <%#= link_to('메인으로 가기', home_main_path, :class => 'ui yellow button') %>-->
<!--      <%# else %>-->
<!--        <a class="ui yellow button" href="/users/sign_up">시작하기<i class="right arrow icon"></i></a>-->
<!--      <%# end %>-->
<!--    </div>-->
    <!--<img src="/images/perform.png" style="width:100%">-->
    <!--<img src="/images/perform2.png" style="width:100%">-->
    <!--<img src="/images/point.png" style="width:100%">-->
    <!--<a href="https://www.facebook.com/imdukk"><h1>https://www.facebook.com/imdukk</h1></a>-->
    <!--<h1>페이스북에서 <strong>'아임덕'</strong>을 검색하세요.</h1>-->
    <!--<br>-->
<!--</div>-->
<!--</div>-->