config/routes.rb
Rails.application.routes.draw do
  root 'visitor#main'
  
  get 'register/info1'
  get 'register/info2'
  post 'register/infoget'

  get 'mission/detail/:id', to: 'mission#detail'

  post 'mission/mission_create'                                                           #작성자가 미션 작성하는 페이지
  post 'mission/performed_mission_create'                                                 #수행자가 미션 작성하는 페이지
  post 'mission/performed_mission_create/:id' => 'mission#performed_mission_create'
   
  post 'home/timeline/profile_img_upload/:id' => 'home#profile_img_upload'
   
  post 'home/timeline/:id' => 'home#timeline'                                       
  get 'mission/mission_destroy/:id' => 'mission#mission_destroy'                                  # 작성자가 본인 미션글 삭제
  get 'mission/performed_mission_destroy/:id' => 'mission#performed_mission_destroy'      # 수행자가 본인 수행글 삭제
  
  get 'mission/mission_editview/:id' => 'mission#mission_editview'                            #작성자 본인 글 수정 내용 입력하는 페이지                                                                                
  post 'mission/mission_edit/:id' => 'mission#mission_edit'                                    #입력한 내용이 임시로 날아갔다가 돌아옴

  get 'mission/performed_mission_editview/:id' => 'mission#performed_mission_editview'                            #작성자 본인 글 수정 내용 입력하는 페이지                                                                                
  post 'mission/performed_mission_edit/:id' => 'mission#performed_mission_edit'    
  
  
  post 'mission/missionComment/:id', to: 'mission#missionComment'
  
  
  
  
  
  
  
  get 'visitor/main'

  get 'home/main'
  get 'home/timeline/:id', to: 'home#timeline'
  get 'home/timeline_temp'
  get 'home/missionLike/:id', to: 'home#missionLike'
  devise_for :users, :controllers => { omniauth_callbacks: 'user/omniauth_callbacks', registrations: "user/registrations", sessions: 'user/sessions' }
  

end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  before_action :set_user, only: [:info1, :info2, :infoget]
  before_action :nickname_nil, only: [:info1, :info2, :infoget]
  before_filter :authenticate_user!
  # 카테고리 선택하기 추가
  def info1
  end

  def info2
  end
  
  def infoget
    
    # 이메일 있음
    unless @user.email.nil?
      @user.nickname = params[:nickname]
      
      
    # 이메일 없음 = twitter
    else
      @user.email = params[:email]
      @user.nickname = params[:nickname]
    end
    
    @user.save
    redirect_to home_main_path
  end
  
  private
    
  def set_user
    @user = current_user
  end
  
  def nickname_nil
    unless @user.nickname.nil?
      redirect_to home_main_path
    end
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/views/register/_additionalInfo.html.erb
<%= form_tag(register_infoget_path, :class => 'ui large form') do %>
  <% if @user.email.nil? or @user.email == '' %>
  <div class="ui raised segment">  
    <div class="field">
      <label for="email" class="ui left aligned header" >email</label>
      <%= text_field_tag :email %>
    </div>
  <% end %>
  
  <div class="field">
    <label for="nickname" class="ui left aligned header" >nickname</label>
    <%= text_field_tag :nickname %>
  </div>
  
  <div class="ui form">
  <div class="inline fields">
    <label for="fruit">관심사를 선택하세요</label>
    <div class="field">
      <div class="ui radio checkbox">
        <%= radio_button_tag :mycategory, "아이돌" %>
        <label>아이돌</label>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= radio_button_tag :mycategory, "게임" %>
        <label>게임</label>
      </div>
    </div>
  </div>
    <%= submit_tag "제출", :class => 'ui fluid large yellow submit button' %>
<% end %>
</div>
</div>
<script>
  $(document).ready(function(){
    $('.ui.radio.checkbox').checkbox();
  });
</script>

app/views/register/info1.html.erb
<div class="ui middle aligned center aligned grid nicForm">
  <div class="column nicColumn">
    <h2 class="ui orange image header nicImage">
      <div class="content">
        닉네임 입력
      </div>
    </h2>
    <%= render 'register/additionalInfo' %>
  </div>
</div>

app/views/register/info2.html.erb
<div class="ui middle aligned center aligned grid nicForm">
  <div class="column nicColumn">
    <h2 class="ui image header nicImage">
      <div class="content">
        이메일, 닉네임 입력
      </div>
    </h2>
    <%= render 'register/additionalInfo' %>
  </div>
</div>